
{% set name = "mercat2" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: https://github.com/raw-lab/mercat2/
  md5: a2e9a113a77dc95324d6f3158a716dc5


build:
  number: 0
  script: python setup.py install

preserve_egg_dir: yes

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - scikit-bio == 0.2.3
    - prodigal
    - dask
    - pandas
    - numpy
    - humanize
    - plotly
    - psutil
    - joblib


test:
  commands:
    - mercat2 --help

about:
  home:
  license: BSD
  summary: 'Mercat2: a versatile counter and diversity estimator for data base independent property analysis obtained from whole community sequencing data.'
  license_family: BSD

extra:
  recipe-maintainers: 
    - raw937
    - rnmouika
    - raw-lab

